Repository ArkEcosystem/ruby-client, pull requests merged in 2019-05, with the labels that each got.

#33 feat: add node/fees endpoint
  lib/arkecosystem/client/api/node.rb
  spec/client/api/node_spec.rb
  spec/spec_helper.rb
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#36 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#38 chore: update sdk url
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#39 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
